### ISSUE TITLE
docker_image :pull - Docker::Error::TimeoutError read timeout reached

### ISSUE THREAD

**Issue by 5f6b3fb8** [bflad/chef-docker#403] opened 2015-08-27 22:16 UTC
I get read timeouts occasionally when using docker_image to pull images. I don't see an option in the documentation or in the code for setting the read timeout.

I don't know if this is related, but I see this in the docker api documentation:

> These methods are prone to read timeouts.  Docker.options[:read_timeout]  will need to be made higher than 60 seconds if expecting a long time between events.

If this is causing the issue, could you make 60 seconds the default, but provide an attribute to override the default for pulls that take longer than 60 seconds.

My current workaround is to login to the host, pull the image, and change the docker_image to action to :pull_if_missing

**Comment by kkeane** [comment] 2015-08-28 09:35
The same issue also applies to docker_image action :build. In that case, the workaround does not apply.

**Comment by kkeane** [comment] 2015-09-15 21:13
This problem is not actually resolved. The problem appears to be in the Docker gem. Looking at the source code for the gem, it seems that the problem is that write_timeout is actually never used at all, and read_timeout is only used for post requests for containers, but not for images nor for get requests in containers.

**Comment by someara** [comment] 2015-09-15 23:31
*sigh*

**Comment by chasebolt** [comment] 2015-09-16 07:49
That is because Docker.options is passed through to excon so you won't see it specifically mentioned in the docker-api gem. This issue originally started out as a timeout with pulling large images, which was resolved. Your issue with docker_image :build I do not believe is related.

As mentioned in the discussion of my pr #406, your issue should be opened as a new issue and examples with some logging would be helpful.

**Comment by chasebolt** [comment] 2015-09-16 07:52
You can also reference this discussion where they use it in dockly.

https://github.com/swipely/docker-api/issues/213#issuecomment-63246018

**Comment by someara** [comment] 2015-09-22 12:00
Closing this... a read_timeout option was added some while back.

It's now set to 120 and can be adjusted as needed.

https://github.com/bflad/chef-docker/blob/18fd423a3fa71e5444484de9d883bc7cc01f9a77/libraries/resource_docker_image.rb#L18

**Closed by someara** 2015-09-22 12:00 UTC
