### ISSUE TITLE
docker installation methods

### ISSUE THREAD

**Issue by st-isidore-de-seville** [bflad/chef-docker#394] opened 2015-08-25 01:14 UTC
Is there a difference between the install method you are using are the install method provided by `wget -qO- https://get.docker.com/ | sh`?  I am wondering if there is some simplicity is have the method from get.docker.com to setup and install the repository with the various init scripts, etc.

This is a wonderful cookbook BTW :+1:

**Comment by someara** [comment] 2015-08-25 01:22
Well that's new... 

Right now the docker_service resource only supports the "old" binary installation method and handles the management of the init scripts itself. In future version of this cookbook, I'll likely pick that apart, and create some dependency cookbooks (yum-docker), to help with hosting repos behind firewalls and stuff like that.

**Comment by st-isidore-de-seville** [comment] 2015-08-25 01:29
I am on a cookbook creating kick and if you would not mind, i could take a stab at just creating the docker cookbook you are referring to that would just manage the repo creation portion of this ... i have the time and i like the experience :smiley: The other question I have is whether or not you would have an interest in supporting native docker package as packaged by debian, ubuntu or provided via EPEL to RHEL and CentOS?

**Comment by someara** [comment] 2015-08-25 01:44
Sure!

There's a yum-* group at github/chef-cookbooks

https://github.com/chef-cookbooks/yum-epel
https://github.com/chef-cookbooks/yum-centos
https://github.com/chef-cookbooks/yum-ius
https://github.com/chef-cookbooks/yum-amazon
(many more)

These are easy, but tedious.

The general pattern is

a) copy yum-centos or whatever to yum-docker
b) make sure test-kitchen has the supported platforms
c) Find, and manually rpm -Uvh the upstream release .rpm onto the system
d) Go into /etc/ and encode all the information you find into attributes
e) make final adjustments

-s

**Comment by st-isidore-de-seville** [comment] 2015-08-25 01:56
I saw another pattern I liked once which was something akin to docker-repo where docker-repo would have three recipes: docker-repo::default, docker-repo::_apt, docker-repo::_yum, etc.  It is one repository cookbook that handles multiple repository formats.  Check out https://github.com/st-isidore-de-seville/cookbook-nginx-repo for something I have released and am working on that uses a similar construct.

Then on top of these *-repo cookbooks, I have been working on another cookbook pattern called, or would be called in this case, docker-pkg (see example for nginx-pkg: https://github.com/st-isidore-de-seville/cookbook-nginx-pkg/tree/feature-initial)

The benefit is that you can use the *-pkg cookbook to either use what I am calling the vendor repository like docker-repo above, or in the case of RHEL or CentOS, it could provide EPEL and control which version of the package to install.

Just some food for thought ... Let me know what you think.

**Comment by st-isidore-de-seville** [comment] 2015-08-25 01:58
The reason I kept the repo cookbooks separate as well is so that people behind a firewall should they choose, can use just that cookbook to mirror the repository behind their firewall and then override the attributes in subsequent usage to pull from their internal private repos.

**Comment by someara** [comment] 2015-08-25 02:05
That works too...

I tend to favor the yum-docker / apt-docker pattern.
It keeps testing matrices smaller by isolating platform groups.

If you loosely couple the dependencies (that is, not putting a depends in
the metadata), It also keeps the attributes loaded onto the node object to
a minimum. (you don't get apt repo data on centos and vice versa)

-s

**Comment by st-isidore-de-seville** [comment] 2015-08-25 02:09
i typically handle that by wrapping my attributes in conditionals.  however, i could do it my way first so you could see it in action then split them out if need be.  at that point, it would be trivial.  either way works for me :smiley:

**Comment by someara** [comment] 2015-08-25 02:11
Let's do it your way!

-s

**Comment by st-isidore-de-seville** [comment] 2015-08-25 02:28
I will put something together.  Give me a few days to do it ...

**Comment by someara** [comment] 2015-08-25 09:12
Looking forward to it

**Comment by someara** [comment] 2015-08-30 11:45
Closing since this is a dupe of #345

**Closed by someara** 2015-08-30 11:45 UTC
