### ISSUE TITLE
detect configuration change and send notification

### ISSUE THREAD

**Issue by KostyaSha** [bflad/chef-docker#490] opened 2015-10-08 14:25 UTC
Is it possible to detect changes in docker_image and docker_container blocks and send notification to the same docker_container block in `:delayed` mode?
Use case: template notifies `:redeploy` in case of change, docker_container notifies when any setting in receipt was changed in this block then in the end of receipt it do only one redeploy (in case of changes from 2 places).

**Comment by someara** [comment] 2015-10-08 14:45
Yes. That is actually the default behavior for Chef notifies / subscribes.

For example,

https://github.com/bflad/chef-docker/blob/fe5966f004785c238d39f1a1d3cd0f6879a7ff07/test/cookbooks/docker_test/recipes/notifications.rb#L27-L28

^ In that scenario, the 'docker_image[alice/bits]' resource subscribes to
both 'file[/alice/Dockerfile]' and 'file[/alice/file]'.

If both of the subscription targets were repaired during the chef-client
run, the :build would only be triggered once, at the end of the run.


-s

**Comment by KostyaSha** [comment] 2015-10-09 20:09
@someara i mean subscribe `docker_image` and `docker_container` changes itself.
I.e. i had
```
docker_container('image') do
 ports "8090:8080"
end
```
and changed to `ports "9090:8080`, so i want trigger pull and then redeploy, or just redeploy itself.

`docker_*` section describes docker command configuration, while file/template is configuration for container internals and for any change of then i want trigger redeploy to ensure that state applied.

**Comment by someara** [comment] 2015-10-09 20:19
Does this work?

```
docker_container('image') do
  ports "8090:8080"
  notifies, :redeploy 'docker_container[image]'
end
```

**Comment by KostyaSha** [comment] 2015-10-09 20:24
Wouldn't this cycle infinitely without `:delayed`?

**Comment by someara** [comment] 2015-10-09 20:29
Actually, docker_container is supposed to redeploy itself on property change anyway

https://github.com/bflad/chef-docker/blob/a50b27e7f8fff89870c66a4b8ecb0e3a1649a478/libraries/provider_docker_container.rb#L199

-s

**Comment by someara** [comment] 2015-10-09 20:41
:delayed is the default timing.

**Comment by KostyaSha** [comment] 2015-10-09 20:52
Will describe my use case
```
file "/srv/docker/container/servers.yml" do
  content YAML.dump( properties)
  notifies :pull, "docker_image['IMAGE']", :delayed
  notifies :redeploy, "docker_container[IMAGE]", :delayed
end

cookbook_file "/srv/docker/container/servers-rabbit.yml" do
  source "servers-rabbit.yml"
  notifies :pull, "docker_image[IMAGE]", :delayed
  notifies :redeploy, "docker_container[IMAGE]", :delayed
end

file "/srv/docker/container/var.sh" do
  content 'export var=somevar'
  notifies :pull, "docker_image[IMAGE]", :delayed
  notifies :redeploy, "docker_container[IMAGE]", :delayed
end

docker_image(IMAGE) do
  tag '3'
  action :nothing
  # notifies :redeploy, "docker_container[IMAGE]", :immediately
end

docker_container(kind_env) do
  action :nothing
  command 'admin'
  tag '3'
  env [
          "XD_CONFIG_LOCATION=file:/mnt/config/",
          "SPRING_PROFILES_ACTIVE=rabbit"
      ]
  binds "/srv/docker/container:/mnt/config/"
  port "#{settings['port-9393']}:9393"
  restart_policy "always"
  # log_driver "journald"
  memory_swap -1
end

```

I want achieve pull+redeploy in case of configuration changes either in files either in docker_container block. I used delayed to have ability merge multiple actions.

**Comment by chasebolt** [comment] 2015-10-09 21:36
My recommendation would be to do it this way. action :pull on an image is idempotent, though there is a small lag as it polls the docker api to verify the current image is up to date. This will result in only 1 image update and the others will be marked as up to date already.

```ruby
file "/srv/docker/container/servers.yml" do
  content YAML.dump( properties)
  notifies :pull, "docker_image['IMAGE']", :immediately
end

cookbook_file "/srv/docker/container/servers-rabbit.yml" do
  source "servers-rabbit.yml"
  notifies :pull, "docker_image[IMAGE]", :immediately
end

file "/srv/docker/container/var.sh" do
  content 'export var=somevar'
  notifies :pull, "docker_image[IMAGE]", :immediately
end

docker_image(IMAGE) do
  tag '3'
  action :nothing
  notifies :redeploy, "docker_container[IMAGE]", :delayed
end

docker_container(kind_env) do
  action :nothing
  command 'admin'
  tag '3'
  env [
    "XD_CONFIG_LOCATION=file:/mnt/config/",
    "SPRING_PROFILES_ACTIVE=rabbit"
  ]
  binds "/srv/docker/container:/mnt/config/"
  port "#{settings['port-9393']}:9393"
  restart_policy "always"
  # log_driver "journald"
  memory_swap -1
end
```

**Comment by someara** [comment] 2015-10-11 17:25
closing this due to inactionability

**Comment by KostyaSha** [comment] 2015-10-12 15:55
@chasebolt in your variant notification about `docker_container` block configuration change is lost

**Comment by KostyaSha** [comment] 2015-10-12 16:00
@chasebolt pull operation is not very fast and doing it multiple times is not efficient :(

**Comment by KostyaSha** [comment] 2015-10-12 16:28
Will 'subscribe` to docker_container from docker_image do the trick with triggering?

**Comment by chasebolt** [comment] 2015-10-12 16:47
That will cause you to pull the image after the container updated. You'd want the image pulled first.

My images always use the default action of :pull and then docker_container either subscribes to the files (or the files notifies).

```ruby
file '/data/test/test.sh' do
  content 'export foo=bar'
  notifies :redeploy, "docker_container[test]"
end

file '/data/test/test2.sh' do
  content 'export hello=world'
  notifies :redeploy, "docker_container[test]"
end

docker_image('alpine') do
  tag 'latest'
  notifies :redeploy, "docker_container[test]"
end

docker_container('test') do
  tag '3'
  command 'sleep 300'
  binds '/data/test:/data'
end```

**Comment by KostyaSha** [comment] 2015-10-12 16:53
@chasebolt if i right understand then in your case container will be redeployed 2 times in case of two files changes.

**Comment by chasebolt** [comment] 2015-10-12 17:01
It will only redeploy once. Delayed notifies or subscribes add resources uniquely to the queue.

**Comment by KostyaSha** [comment] 2015-10-12 17:57
If delayed is default, then on every chef run you will do pull. I think for latest it makes sense, but for static image it may cause run failure in case of registry unavailability while pull is not expected at all. As temp solution it may work but not ideal.

**Comment by chasebolt** [comment] 2015-10-12 18:02
```ruby
file '/data/test/test.sh' do
  content 'export foo=bar'
  notifies :pull, "docker_image[alpine]"
  notifies :redeploy, "docker_container[test]"
end

file '/data/test/test2.sh' do
  content 'export hello=world'
  notifies :pull, "docker_image[alpine]"
  notifies :redeploy, "docker_container[test]"
end

docker_image('alpine') do
  tag 'latest'
  notifies :redeploy, "docker_container[test]"
end

docker_container('test') do
  tag '3'
  command 'sleep 300'
  binds '/data/test:/data'
  action :run
end
```

**Comment by someara** [comment] 2015-10-12 18:51
re-opening this so I can find it

**Comment by chasebolt** [comment] 2015-10-12 22:31
@jkeiser figured this one out. this is the working monkey patch that would go into your recipe.

https://gist.github.com/chasebolt/4a3ff4aac332a66c392e

**Comment by someara** [comment] 2015-10-12 23:40
Thats.... interesting. I think there's a more approachable solution.

For anyone stumbling upon this thread:

The root the problem is this.
https://gist.github.com/someara/ef5d381ff54535d3a353#file-two_restarts-rb-L9

^ In that example, the Chef starts 'service[foo]', then restarts it. 
Because we told it to. The delated notifications happen after the converge phase is complete.

The shortest path to happy is going to be to use a marker like this.

https://gist.github.com/someara/c79d29063570a4f669ca

**Comment by chasebolt** [comment] 2015-10-13 00:34
while i agree the shortest path to happy is just to accept a double restart in this case and move on.

i dont think the marker file adds anything here. when you create the marker file, the notifies restart will never trigger on subsequent template changes.

**Comment by KostyaSha** [comment] 2015-10-13 00:35
Double restart may end with devicemapper dead containers :(

**Comment by someara** [comment] 2015-10-13 03:01
> I don't think the marker file adds anything here. when you create the marker file, the notifies restart will > never trigger on subsequent template changes.

I just fixed the logic in the gist from "unless" to "if", so it works now. However, the double restart problem would still remain if a property on a docker_service triggers a redeploy + another from the notification queue.

The devicemapper thing should get better once the package repo support is implemented. 
In the short term, switching to overlayfs may mitigate it as well.

I'm going to close this issue for now, since it's really a Chef level issue. 

However, I'm going to open a new one to make sure the docker_container actions poll for completion.
-s

**Closed by someara** 2015-10-13 03:01 UTC

**Comment by KostyaSha** [comment] 2015-10-16 17:24
Just to keep it here (continue debugging). 
- Double redeploy may kill DB setups that may happen on startup.
- Containers shutdown should support time value to have graceful shutdown without data corruption (the same for restart)

**Comment by dud225** [comment] 2020-06-19 15:19
It would be great to have this issue be eventually addressed.
