### ISSUE TITLE
Error with berks install and windows: No such file or directory

### ISSUE THREAD

**Issue by 5f6b3fb8** [bflad/chef-docker#357] opened 2015-08-05 21:15 UTC
It seems like the docker-api-1.22.0 spec folder structure is nested with large directory names. The path is larger than what windows supports.

My dev machine is windows 2012 r2/virtualbox5/vagrant 1.7.4/chefdk 0.6.2.

metadata.rb has 
depends 'docker', '0.43.0'

When I run 'berks install' I get the following error:

Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
Installing docker (0.42.0)
E, [2015-08-05T13:05:34.629136 #5140] ERROR -- : Actor crashed!
Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/.../AppData/Local/Temp/1/d20150805-5140-y9h85x/doc
ker/files/default/vendor/gems/docker-api-1.22.0/spec/vcr/Docker_Image/_build_from_dir/with_a_valid_Dockerfile/with_a_blo
ck_capturing_build_output/uses_a_cached_version_the_second_time/calls_the_block_and_passes_build_output.yml

**Comment by habelson** [comment] 2015-08-12 17:36
I too have started seeing this problem, I am using 0.37.0, I have a feeling it is related to changed in the docker-api gem. My first thought was windows path length limits

**Comment by rhutzel** [comment] 2015-08-12 17:51
My Windows box can't clone this Git repo for the same reason.
```
$ git clone git@github.com:bflad/chef-docker.git
....
error: unable to create file files/default/vendor/gems/docker-api-1.22.0/spec/vcr/Docker_Image/_build_from_dir/with_a_valid_Dockerfile/with_a_block_capturing_build_output/uses_a_cached_version_the_second_time/calls_the_block_and_passes_build_output.yml (Filename too long)
```

**Comment by someara** [comment] 2015-08-13 20:47
Dupe of #351

**Comment by someara** [comment] 2015-08-13 21:32
This actually wasn't a dupe.

**Comment by someara** [comment] 2015-08-13 21:32
I've removed the spec and test directories from the vendored gems... that should get rid of the ridiculously long filenames.

**Closed by someara** 2015-08-13 21:32 UTC
Labels: bug
