### ISSUE TITLE
docker_container resource doesn't respect tag

### ISSUE THREAD

**Issue by marcogallotta** [bflad/chef-docker#422] opened 2015-09-14 23:34 UTC
See https://github.com/bflad/chef-docker/blob/master/libraries/provider_docker_container.rb#L195

This code just specifies an image name, and doesn't respect the tag. The init script contains just "/usr/bin/docker start -a image".

**Comment by someara** [comment] 2015-09-15 00:50
I'm trying to grok what you're saying here... 

You're using :start instead of :run without doing a :create first?

-s

**Comment by marcogallotta** [comment] 2015-09-15 03:03
We have the following code:

    docker_container 'grafana' do
      detach true
      env grafana_env
      port '3000:3000'
      tag node['grafana']['version']
    end

Which I'd expect to run the `grafana:node['grafana']['version']` image, but it just runs `grafana` with no tag specified.

**Comment by marcogallotta** [comment] 2015-09-15 03:10
The root issue we are trying to solve is that when we build a new image with an increased version, and try to run it, we still end up running the older version.

**Comment by someara** [comment] 2015-09-15 07:14
The default action on `docker_service` is :run_if_missing ... try specifying :run instead

**Comment by someara** [comment] 2015-09-15 14:53
For the record, the tag is definitely being respected.. :run converges where through the :create state (where the tag is references to create the container), and then the :start state, which you linked to.

The problem is you're not specifying an action, so it's using the default of :run_if_missing, which doesn't apply the changes on the next converge.

Closing because this is expected behavior...
Making a note that maybe :run should be the default in the next major release

**Closed by someara** 2015-09-15 14:53 UTC
Labels: invalid, question

**Comment by chasebolt** [comment] 2015-09-15 16:07
I like the idea of run being default. If I stop a container manually, next
time I run chef it should make sure all the containers are running again.
