### ISSUE TITLE
docker_container bind attribute is reversed

### ISSUE THREAD

**Issue by kkeane** [bflad/chef-docker#492] opened 2015-10-09 07:07 UTC
In the 1.0.49 version of the cookbook and docker 1.7.1 (and possibly other versions), the container path and the host path are reversed.

Example:

docker create -v /somehostpath:/tmp myimage

Will mount the host's /somehostpath into the container's /tmp directory.

When specifying the same string in the bind attribute, the host's /tmp will be mounted into the container's /somehostpath.

It looks like this might be loosely related to #428 although it is not the same issue.

**Comment by someara** [comment] 2015-10-09 17:47
That's pretty bizarre....

Binds is exercised in the test cookbook here

https://github.com/bflad/chef-docker/blob/a50b27e7f8fff89870c66a4b8ecb0e3a1649a478/test/integration/resources-171/serverspec/assert_functioning_spec.rb#L267

and verified here

https://github.com/bflad/chef-docker/blob/a50b27e7f8fff89870c66a4b8ecb0e3a1649a478/test/integration/resources-171/serverspec/assert_functioning_spec.rb#L267

-s

**Comment by chasebolt** [comment] 2015-10-09 17:55
the first link for the test cookbook should be
https://github.com/bflad/chef-docker/blob/a50b27e7f8fff89870c66a4b8ecb0e3a1649a478/test/cookbooks/docker_test/recipes/container.rb#L255-L261

**Comment by someara** [comment] 2015-10-11 17:24
I can't reproduce this... closing for now. Please re-open if this is an issue in 2.x

**Closed by someara** 2015-10-11 17:24 UTC

**Comment by kkeane** [comment] 2015-10-11 18:51
It's very odd. I can't reproduce it in a test case scenario, either, so I need to further isolate the situation when it occurs.

**Comment by kkeane** [comment] 2015-10-12 00:57
Odd - I can't reproduce it even with my production cookbooks. I recently switched from the docker engine in the EPEL repository to the "official" one from the docker repository - maybe it was a bug in the EPEL version of docker.
